package hr.java.projekt.entitet;

public enum Genre {
    ACTION, ADVENTURE, AVANT_GARDE, AWARD_WINNING, COMEDY, DRAMA, FANTASY, GOURMET, HORROR, MYSTERY, ROMANCE, SCI_FI, SLICE_OF_LIFE, SPORTS, SUPERNATURAL, SUSPENSE

}
